### PR TITLE
Support MacOS for Carthage Dependencies

### LINKED ISSUE #4: Carthage Support for MacOS
When trying to consume this into a MacOS based project using Carthage, I get the error:

```
$ carthage bootstrap --platform macOS --cache-builds --verbose
<snip>
*** Skipped building secp256k1.swift due to the error: 
Dependency "secp256k1.swift" has no shared framework schemes for any of the platforms: Mac
```

Is this a supported configuration?

### PR DESCRIPTION
**Pull request by keefertaylor**
Building this library for MacOS with Carthage previously resulted in an error (see #4). 

I performed the following steps to upgrade the .xcodeproj for MacOS compatibility with Carthage:
- Open xcodeproj, run all update scripts recommended by XCode (swift 5 migration, etc)
- Set `supportedPlatforms` to `macosx`, `iphoneos`, `iphonesimulator` in build configuration
- Replace `#import <UIKit/UIKit.h>` with `#import <Foundation/Foundation.h>`. UIKit imports Foundation, but the source files do not use any UIKit based classes and UIKit is not available on MacOS.

To test, I verified that my Carthage based project can now build this library on both iOS and OSX (example PR with continuous CI: https://github.com/keefertaylor/TezosKit/pull/153).

---
Fixes #4

### CODE REVIEW

**Comment by Ybrin** [comment]
Please make sure Travis completes successfully

**Comment by Ybrin** [comment]
Done?

**Comment by keefertaylor** [comment]
Apologies that this is stale. I'll poke at this today and see if I can get it working.

**Comment by keefertaylor** [comment]
It isn't immediately clear to me why this is failing. 

There's a couple variables here:
- You're using a pretty old 2+ years image of XCode (9.2 vs the current 11.3)
- Your dependencies are out of date (so I can't easily upgrade to a modern version of xcode)
- After upgrading, I get missing rpath@ errors, for reasons I can't discern

Without updating, I can't get this to build locally and reproduce the failures we see on CI. I do *believe* this PR works though (and I am actually consuming this PR in a production project from my fork), it's just that the testbed project isn't passing. 

I opened #9 to address changes to the build system. I'm confident if we can get that to a passing state then we should be able to make this PR pass CI quite easily.

**Comment by keefertaylor** [comment]
Update: I actually believe this project is broken at head, see #10. 

I no longer believe that build breaks are related to this PR.

**Comment by Ybrin** [comment]
@keefertaylor Can you see the actual error message? I will try to fix this at head so we can apply it here.

**Pull request closed without merging**
