### PR TITLE
Remove invalid paths from Package.swift

### LINKED ISSUE #13: Xcode 13 warnings modules/ecdh + modules/recovery file not found
Trying to update my Swift package to use Xcode 13. Getting several warnings about missing files. Can someone add these?

Screenshot 2021-10-07 at 11 33 13

### PR DESCRIPTION
**Pull request by simonmcl**
Fixes: https://github.com/Boilertalk/secp256k1.swift/issues/13

### CODE REVIEW

**Comment by koraykoska** [comment]
@simonmcl Does this have any implications?

**Review by nestorgt — APPROVED** [review]

**Comment by arnauddorgans** [comment]
up

**Comment by simonmcl** [comment]
@koraykoska bump

**Comment by CassiusPacheco** [comment]
Hi there @koraykoska, any chance we might get this merged in? We should also update the cocoapods version to the latest. Let me know if I can help somehow

**Comment by koraykoska** [comment]
@simonmcl I commented in #13 

@CassiusPacheco We are not supporting Cocoapods anymore with any of our libraries. The reason all Cocoapods files and directories were not removed yet is that this library is meant mainly as a dependency of [Web3.swift](https://github.com/Boilertalk/Web3.swift). I will try to remove all Cocoapods specific things in the coming weeks. Please start using Swift Package Manager and see here for the rationale and how to opt-in even if you have to use Cocoapods: https://github.com/Boilertalk/Web3.swift#cocoapods-and-carthage

**Pull request closed without merging**
