### PR TITLE
add ecdh and recovery module

### PR DESCRIPTION
**Pull request by ph4r05**

### CODE REVIEW

**Comment by Ybrin** [comment]
Explain please

**Comment by ph4r05** [comment]
ECDH module is not included, i.e., `ENABLE_MODULE_ECDH` is not defined, thus ECDH functionality defined in https://github.com/Boilertalk/secp256k1/blob/d5407179912e8c1f825a212a474aaa86b10f1352/include/secp256k1_ecdh.h#L20 is not compiled in. Linking fails. 
https://github.com/Boilertalk/secp256k1/blob/d5407179912e8c1f825a212a474aaa86b10f1352/src/secp256k1.c#L591

**Comment by ph4r05** [comment]
ping

**Comment by Ybrin** [comment]
Make sure Travis completes successfully.

**Comment by ph4r05** [comment]
OK I will check that out

**Comment by AlexanderOsokin** [comment]
Please, merge this PR. We are losing important functionality

**Comment by ph4r05** [comment]
Ah I forgot about the Travis. I will check that out

**Comment by AlexanderOsokin** [comment]
This problem may be related to #10

**Comment by ph4r05** [comment]
The build problem is still present. I have no idea why

**Comment by simonmcl** [comment]
I've fixed the travis issues here: https://github.com/Boilertalk/secp256k1.swift/pull/14 tagged the owner to try get it merged, to unblock this PR

**Comment by simonmcl** [comment]
@ph4r05 The PR containing a fix for the Travis CI build issue has been merged in. Can you rebase this PR on the latest code to avoid this failure. Really keen to get this merged in and tagged

**Comment by ph4r05** [comment]
@simonmcl rebased

**Comment by simonmcl** [comment]
@ph4r05 thanks! 

@koraykoska can we get this one merged in and then tag a new version, hopefully this gets rid of the Xcode warnings

**Comment by koraykoska** [comment]
@ph4r05 @simonmcl Done. Thanks for your contributions.

**Comment by koraykoska** [comment]
@ph4r05 @simonmcl Tagged as well. https://github.com/Boilertalk/secp256k1.swift/releases/tag/0.1.5

**Comment by simonmcl** [comment]
@ph4r05 i'm getting this error when trying to use `0.1.5` as part of a swift package. Can you have a look and see what the issue might be?

Screenshot 2022-02-09 at 09 36 52

**Comment by simonmcl** [comment]
@ph4r05 never mind, looks like it was fixed here: https://github.com/Boilertalk/secp256k1.swift/pull/15

**Pull request merged**
